apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jira-localHome
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jira/localHome
